version: '3.8'

networks:
  aether-network:
    driver: bridge

services:
  aetherconnect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Only API Gateway exposed
    networks:
      - aether-network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      
      # Database URLs
      - POSTGRES_URL=postgresql://postgres.thijnzgwuwkpkdddctdm:IxwcwREzsswjBvDM@aws-1-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - MONGODB_URL=mongodb+srv://thura:KlFe8bUKMM8yGRVB@cluster0.w6nkg1u.mongodb.net/aetherconnect?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URL=rediss://default:AdDsAAIncDEzZWQ4OTAzYTRkYWI0NzMzOWU5MzAwNDgwZWZjNTYxOXAxNTM0ODQ@on-stag-53484.upstash.io:6379
      
      # JWT Configuration
      - JWT_SECRET=your-super-secret-access-key-change-in-production-2025
      - JWT_WS_SECRET=your-super-secret-ws-key-change-in-production-2025
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-in-production-2025
      
      # Service Ports (internal only)
      - API_GATEWAY_PORT=3000
      - AUTH_SERVICE_GRPC_PORT=50001
      - MESSAGE_SERVICE_GRPC_PORT=50002
      - MESSAGE_SERVICE_HTTP_PORT=3002
      
      # Internal Service URLs (localhost for single container)
      - AUTH_SERVICE_GRPC_URL=localhost:50001
      - MESSAGE_SERVICE_GRPC_URL=localhost:50002
      - FRONTEND_URL=http://localhost:3004
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
